{
   "users" : [
      {
         "user" : {
            "content" : {
               "email" : "support@gooddata.com",
               "firstname" : "GoodData",
               "userRoles" : [
                  "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/roles/1"
               ],
               "phonenumber" : "415-200-0194",
               "status" : "ENABLED",
               "lastname" : "Support",
               "login" : "support@gooddata.com"
            },
            "links" : {
               "roles" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/e4f3d62030e613e04fb6dcdeda474343/roles",
               "permissions" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/e4f3d62030e613e04fb6dcdeda474343/permissions",
               "groups" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/e4f3d62030e613e04fb6dcdeda474343/groups",
               "self" : "/gdc/account/profile/e4f3d62030e613e04fb6dcdeda474343",
               "invitations" : "/gdc/account/profile/e4f3d62030e613e04fb6dcdeda474343/invitations",
               "projects" : "/gdc/account/profile/e4f3d62030e613e04fb6dcdeda474343/projects",
               "projectRelUri" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/e4f3d62030e613e04fb6dcdeda474343"
            },
            "meta" : {
               "created" : "2010-03-05 19:09:56",
               "updated" : "2012-10-25 10:29:09",
               "author" : "/gdc/account/profile/876ec68f5630b38de65852ed5d6236ff",
               "title" : "GoodData Support",
               "contributor" : "/gdc/account/profile/e4f3d62030e613e04fb6dcdeda474343"
            }
         }
      },
      {
         "user" : {
            "content" : {
               "email" : "john.collins@greatvines.com",
               "firstname" : "John",
               "userRoles" : [
                  "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/roles/1"
               ],
               "phonenumber" : "7079687560",
               "status" : "ENABLED",
               "lastname" : "Collins",
               "login" : "john.collins@greatvines.com"
            },
            "links" : {
               "roles" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/37d772d8db4f1752d11c03f7a277af84/roles",
               "permissions" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/37d772d8db4f1752d11c03f7a277af84/permissions",
               "groups" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/37d772d8db4f1752d11c03f7a277af84/groups",
               "self" : "/gdc/account/profile/37d772d8db4f1752d11c03f7a277af84",
               "invitations" : "/gdc/account/profile/37d772d8db4f1752d11c03f7a277af84/invitations",
               "projects" : "/gdc/account/profile/37d772d8db4f1752d11c03f7a277af84/projects",
               "projectRelUri" : "/gdc/projects/h4wsx6lg87g5l4ipzgjwy2h2xql2d15p/users/37d772d8db4f1752d11c03f7a277af84"
            },
            "meta" : {
               "created" : "2011-02-08 01:16:43",
               "updated" : "2012-10-09 14:46:39",
               "author" : "/gdc/account/profile/876ec68f5630b38de65852ed5d6236ff",
               "title" : "John Collins",
               "contributor" : "/gdc/account/profile/37d772d8db4f1752d11c03f7a277af84"
            }
         }
      }
   ]
}